'use server';

/**
 * @fileOverview AI-powered homework analysis flow for text input.
 *
 * - analyzeHomeworkText - Analyzes the provided text to detect potential AI generation.
 * - AnalyzeHomeworkTextInput - The input type for the analyzeHomeworkText function.
 * - AnalyzeHomeworkTextOutput - The return type for the analyzeHomeworkText function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AnalyzeHomeworkTextInputSchema = z.object({
  text: z
    .string()
    .describe('The homework text to analyze for potential AI generation.'),
});
export type AnalyzeHomeworkTextInput = z.infer<typeof AnalyzeHomeworkTextInputSchema>;

const AnalyzeHomeworkTextOutputSchema = z.object({
  isAiGenerated: z
    .boolean()
    .describe('Whether the homework text was likely generated by AI.'),
  confidenceScore: z
    .number()
    .describe(
      'A score (0-1) indicating the confidence level of AI generation detection.'
    ),
});
export type AnalyzeHomeworkTextOutput = z.infer<typeof AnalyzeHomeworkTextOutputSchema>;

export async function analyzeHomeworkText(
  input: AnalyzeHomeworkTextInput
): Promise<AnalyzeHomeworkTextOutput> {
  return analyzeHomeworkTextFlow(input);
}

const determineConfidenceScore = ai.defineTool({
  name: 'determineConfidenceScore',
  description: 'This tool determines the confidence score based on the AI analysis of the text.',
  inputSchema: z.object({
    analysisResult: z.string().describe('The analysis result of the homework text.'),
  }),
  outputSchema: z.number().describe('The confidence score (0-1) for AI generation.'),
},
async (input) => {
  // Implement logic to determine the confidence score based on the analysis result.
  // This is a placeholder; replace with actual implementation.
  const analysis = input.analysisResult.toLowerCase();
  if (analysis.includes('likely ai-generated')) {
    return 0.85; // High confidence
  } else if (analysis.includes('possibly ai-generated')) {
    return 0.6;
  } else {
    return 0.2; // Low confidence
  }
});

const analyzeHomeworkTextPrompt = ai.definePrompt({
  name: 'analyzeHomeworkTextPrompt',
  tools: [determineConfidenceScore],
  input: {schema: AnalyzeHomeworkTextInputSchema},
  output: {schema: AnalyzeHomeworkTextOutputSchema},
  prompt: `You are an AI detection assistant.

  Analyze the following homework text to determine if it was likely generated by AI.

  Homework Text: {{{text}}}

  Respond with whether or not this text was AI generated and a brief explanation.

  If the user's question asks about the likelihood of AI generation, call the determineConfidenceScore tool to get the AI generation confidence score using tool.
  `,
});

const analyzeHomeworkTextFlow = ai.defineFlow(
  {
    name: 'analyzeHomeworkTextFlow',
    inputSchema: AnalyzeHomeworkTextInputSchema,
    outputSchema: AnalyzeHomeworkTextOutputSchema,
  },
  async input => {
    const {output} = await analyzeHomeworkTextPrompt(input);

    // Call tool to determine confidence score
    const confidenceScore = await determineConfidenceScore({
      analysisResult: `The homework text was ${output?.isAiGenerated ? 'likely' : 'not'} AI generated.`, // Pass the analysis result
    });


    return {
      isAiGenerated: output!.isAiGenerated,
      confidenceScore,
    };
  }
);
