'use server';

/**
 * @fileOverview AI-powered homework analysis flow for text input.
 *
 * - analyzeHomeworkText - Analyzes the provided text to detect potential AI generation.
 * - AnalyzeHomeworkTextInput - The input type for the analyzeHomeworkText function.
 * - AnalyzeHomeworkTextOutput - The return type for the analyzeHomeworkText function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AnalyzeHomeworkTextInputSchema = z.object({
  text: z
    .string()
    .describe('The homework text to analyze for potential AI generation.'),
});
export type AnalyzeHomeworkTextInput = z.infer<typeof AnalyzeHomeworkTextInputSchema>;

const AnalyzeHomeworkTextOutputSchema = z.object({
  isAiGenerated: z
    .boolean()
    .describe('Whether the homework text was likely generated by AI.'),
  confidenceScore: z
    .number()
    .describe(
      'A score (0-1) indicating the confidence level of AI generation detection.'
    ),
  explanation: z
    .string()
    .describe('A brief explanation for the given confidence score.'),
});
export type AnalyzeHomeworkTextOutput = z.infer<typeof AnalyzeHomeworkTextOutputSchema>;

export async function analyzeHomeworkText(
  input: AnalyzeHomeworkTextInput
): Promise<AnalyzeHomeworkTextOutput> {
  return analyzeHomeworkTextFlow(input);
}

const analyzeHomeworkTextPrompt = ai.definePrompt({
  name: 'analyzeHomeworkTextPrompt',
  input: {schema: AnalyzeHomeworkTextInputSchema},
  output: {schema: AnalyzeHomeworkTextOutputSchema},
  config: {
    temperature: 0.1,
  },
  prompt: `You are a world-class AI Writing Detection Expert, known for your ability to spot sophisticated AI-generated text. Your analysis is strict and nuanced.

**Primary AI Writing Characteristics to Look For:**
*   **Overly Polished & Uniform Tone:** The writing is too clean. Every sentence is well-constructed, the tone is perfectly consistent, and there is a noticeable lack of a unique, personal voice. It feels generic, like it could have been written by anyone.
*   **Perfectly Logical Structure:** The ideas flow too perfectly from one to the next, with flawless transitions. Human writing often has slight jumps in logic or less-than-perfect organization.
*   **Robotic Transitions & Predictable Vocabulary:** Look for an over-reliance on words like "delve," "tapestry," "leverage," "robust," "navigate," "furthermore," "moreover," and "in conclusion." These are strong indicators.
*   **Lack of a Genuine Voice:** Human writing, even formal writing, contains subtle personality. It might have a distinct rhythm, occasional awkward phrasing, or a clear point of view. AI text often lacks this soul.

**IMPORTANT:** Be highly critical. Do not be easily fooled by text that is simply well-written. Your job is to find the subtle tells of AI. A high confidence score requires strong evidence of the patterns above.

Analyze the following text:

'''
{{{text}}}
'''

Based on your strict analysis, determine:
1.  **isAiGenerated**: Set to true if you are confident it's AI. Be skeptical and have a high bar.
2.  **confidenceScore**: A score from 0.0 to 1.0. A score above 0.6 indicates likely AI involvement. A score above 0.8 requires very strong evidence.
3.  **explanation**: Briefly explain your reasoning. Cite specific examples of robotic phrasing, uniform tone, or other AI tells.
`,
});

const analyzeHomeworkTextFlow = ai.defineFlow(
  {
    name: 'analyzeHomeworkTextFlow',
    inputSchema: AnalyzeHomeworkTextInputSchema,
    outputSchema: AnalyzeHomeworkTextOutputSchema,
  },
  async input => {
    const {output} = await analyzeHomeworkTextPrompt(input);
    return output!;
  }
);
