'use server';

/**
 * @fileOverview AI-powered homework analysis flow for text input.
 *
 * - analyzeHomeworkText - Analyzes the provided text to detect potential AI generation.
 * - AnalyzeHomeworkTextInput - The input type for the analyzeHomeworkText function.
 * - AnalyzeHomeworkTextOutput - The return type for the analyzeHomeworkText function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AnalyzeHomeworkTextInputSchema = z.object({
  text: z
    .string()
    .describe('The homework text to analyze for potential AI generation.'),
});
export type AnalyzeHomeworkTextInput = z.infer<typeof AnalyzeHomeworkTextInputSchema>;

const AnalyzeHomeworkTextOutputSchema = z.object({
  isAiGenerated: z
    .boolean()
    .describe('Whether the homework text was likely generated by AI.'),
  confidenceScore: z
    .number()
    .describe(
      'A score (0-1) indicating the confidence level of AI generation detection.'
    ),
  explanation: z
    .string()
    .describe('A brief explanation for the given confidence score.'),
});
export type AnalyzeHomeworkTextOutput = z.infer<typeof AnalyzeHomeworkTextOutputSchema>;

export async function analyzeHomeworkText(
  input: AnalyzeHomeworkTextInput
): Promise<AnalyzeHomeworkTextOutput> {
  return analyzeHomeworkTextFlow(input);
}

const analyzeHomeworkTextPrompt = ai.definePrompt({
  name: 'analyzeHomeworkTextPrompt',
  input: {schema: AnalyzeHomeworkTextInputSchema},
  output: {schema: AnalyzeHomeworkTextOutputSchema},
  prompt: `You are an expert AI detection assistant. Your task is to analyze a given text and determine if it was written by an AI.

Analyze the following homework text:

'''
{{{text}}}
'''

Based on your analysis, determine:
1.  **isAiGenerated**: A boolean value (true/false) indicating if the text is likely AI-generated.
2.  **confidenceScore**: A score between 0.0 and 1.0 representing your confidence in this determination. A score of 1.0 means you are 100% certain it is AI-generated, and 0.0 means you are certain it is not.
3.  **explanation**: A brief explanation of your reasoning, highlighting the specific linguistic patterns, style, or artifacts that led to your conclusion.
`,
});

const analyzeHomeworkTextFlow = ai.defineFlow(
  {
    name: 'analyzeHomeworkTextFlow',
    inputSchema: AnalyzeHomeworkTextInputSchema,
    outputSchema: AnalyzeHomeworkTextOutputSchema,
  },
  async input => {
    const {output} = await analyzeHomeworkTextPrompt(input);
    return output!;
  }
);
