'use server';
/**
 * @fileOverview Detects AI-generated content in a PDF file.
 *
 * - detectAIGeneratedContentInPDF - A function that handles the detection of AI-generated content in a PDF.
 * - DetectAIGeneratedContentInPDFInput - The input type for the detectAIGeneratedContentInPDF function.
 * - DetectAIGeneratedContentInPDFOutput - The return type for the detectAIGeneratedContentInPDF function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const DetectAIGeneratedContentInPDFInputSchema = z.object({
  pdfDataUri: z
    .string()
    .describe(
      'A PDF file as a data URI that must include a MIME type and use Base64 encoding. Expected format: \'data:<mimetype>;base64,<encoded_data>\'.'
    ),
});
export type DetectAIGeneratedContentInPDFInput = z.infer<typeof DetectAIGeneratedContentInPDFInputSchema>;

const DetectAIGeneratedContentInPDFOutputSchema = z.object({
  analysisResult: z
    .string()
    .describe('The analysis result indicating the likelihood of AI-generated content.'),
  confidenceScore: z.number().describe('A confidence score (0-1) indicating the likelihood of AI generation.'),
});
export type DetectAIGeneratedContentInPDFOutput = z.infer<typeof DetectAIGeneratedContentInPDFOutputSchema>;

export async function detectAIGeneratedContentInPDF(
  input: DetectAIGeneratedContentInPDFInput
): Promise<DetectAIGeneratedContentInPDFOutput> {
  return detectAIGeneratedContentInPDFFlow(input);
}

const detectAIGeneratedContentInPDFPrompt = ai.definePrompt({
  name: 'detectAIGeneratedContentInPDFPrompt',
  input: {schema: DetectAIGeneratedContentInPDFInputSchema},
  output: {schema: DetectAIGeneratedContentInPDFOutputSchema},
  prompt: `You are an AI content detection expert. Analyze the text extracted from the following PDF and determine if any sections were likely generated by AI. Provide a confidence score (0-1) indicating the likelihood of AI generation.

PDF Content: {{pdfDataUri}}`,
});

const detectAIGeneratedContentInPDFFlow = ai.defineFlow(
  {
    name: 'detectAIGeneratedContentInPDFFlow',
    inputSchema: DetectAIGeneratedContentInPDFInputSchema,
    outputSchema: DetectAIGeneratedContentInPDFOutputSchema,
  },
  async input => {
    const {output} = await detectAIGeneratedContentInPDFPrompt(input);
    return output!;
  }
);
